### ISSUE TITLE
Can't train MelGAN-STFT discriminator

### ISSUE THREAD

**Issue by ZDisket** [dathudeptrai/TensorflowTTS#22]
I have been training MelGAN-STFT by finetuning it on the LJSpeech model. When it gets to `discriminator_train_start_steps`, it stops and tells me to restart. When I restart with the discriminator on less than the steps of the latest checkpoint (210k vs 220k), I get this:

```
ValueError: in user code:

    <ipython-input-13-8bd0e2e9cdea>:110 _one_step_generator  *
        p_hat = self.discriminator(y_hat)
    /content/TensorflowTTS/tensorflow_tts/models/melgan.py:441 call  *
        outs += [f(x)]
    /content/TensorflowTTS/tensorflow_tts/models/melgan.py:386 call  *
        x = f(x)
    /content/TensorflowTTS/tensorflow_tts/utils/group_conv.py:283 call  *
        self._convolution_op = nn_ops.Convolution(
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/nn_ops.py:1063 __init__  **
        filter_shape[num_spatial_dims]))

    ValueError: number of input channels does not match corresponding dimension of filter, 16 != 4
```
Also, all my [predictions ](https://drive.google.com/drive/folders/1-GYe5NPZ7MFRoz4NbX-oshPF-4cvlJKX?usp=sharing)have heavy metallic noise. I'm assuming this is due to lack of discriminator training.

**Comment by dathudeptrai** [comment]
@ZDisket https://github.com/dathudeptrai/TensorflowTTS/blob/master/tensorflow_tts/utils/group_conv.py#L283. Plese repce nn_ops.Convolution to Convolution. That is a mismatch between my local code and public code, sorry, fix now :)). You need to train around 700-800k to have a good quality :D.

**Comment by dathudeptrai** [comment]
BTW, what is ur training speed :D

**Comment by ZDisket** [comment]
@dathudeptrai 
> BTW, what is ur training speed :D

About 10.8it/s on a P100.

**Comment by dathudeptrai** [comment]
@ZDisket too fast :)) how about tacotron now ?

**Comment by ZDisket** [comment]
@dathudeptrai 

I don't have it right now but I don't remember it changing from the last figure I told you earlier.

**Comment by dathudeptrai** [comment]
ok :D. Ur dataset seem very good :)). I like the emotion speech :)))

**Comment by ZDisket** [comment]
@dathudeptrai 
If you like it that much then you can have it. It's the least I can do after you made this awesome repo and helped me.

**Comment by dathudeptrai** [comment]
@ZDisket t thought that is private dataset and cann't be share ?

**Comment by ZDisket** [comment]
@dathudeptrai 
It's "private" as in only me and a few others know about its existence, but not private as in that it's forbidden or problematic to share it.

**Comment by dathudeptrai** [comment]
@ZDisket it' good if you make pull request to share an audio samples end2end or pretrained model for that datasets (Don't need share dataset :D). That will prove that model in this repo can be train efficiently on expressive dataset

**Comment by ZDisket** [comment]
@dathudeptrai If the model turns out good, can I email you the models and audio samples instead? I'm not entirely familiar with this repo's organization.

**Comment by dathudeptrai** [comment]
@ZDisket  yes, you can. I will copyright of you.
