### ISSUE TITLE
Tacotron2 end2end sample

### ISSUE THREAD

**Issue by khanhlvg** [dathudeptrai/TensorflowTTS#25]
Could you provide a end2end sample showing how to use the Tacotron2 pretrained model? I tried to reach the source code but couldn't figure out what to feed to each parameter.

Thanks!

**Comment by dathudeptrai** [comment]
@khanhlvg pls, decode_tacotron.py on examples/tacotron2. There are many thing for me todo now :)), i will create colab and github pages :)) it will take some times

**Comment by dathudeptrai** [comment]
@khanhlvg https://github.com/dathudeptrai/TensorflowTTS/blob/master/notebooks/tacotron2_inference.ipynb
