### ISSUE TITLE
How to implement Tacotron2 model without using tensorflow_addons library ?

### ISSUE THREAD

**Issue by xiaoyangnihao** [dathudeptrai/TensorflowTTS#28]
Api in tensorflow_addons  seems a little complicated, can somene implement tacotron2 model, especically the Attention module and Decode model, just like the way in Pytorch?

**Comment by dathudeptrai** [comment]
@xiaoyangnihao why you don't want use tf_addons, it is great, better abstract. If you want to know how to implement tacotron 2 without tf_addons, pls ref https://github.com/dathudeptrai/TensorflowTTS/blob/c5970e5d5a2999f6f6a3b9631f75f2597658a960/tensorflow_tts/layers/tacotron2.py, https://github.com/dathudeptrai/TensorflowTTS/blob/c5970e5d5a2999f6f6a3b9631f75f2597658a960/tensorflow_tts/models/tacotron2.py. The code is just for refference, i'm not sure if it can be train and learn alignment :)).
