### ISSUE TITLE
converting fastspeech model to tflite

### ISSUE THREAD

**Issue by manmay-nakhashi** [dathudeptrai/TensorflowTTS#37]
can we convert Fastspeech model to tflite ?

**Comment by dathudeptrai** [comment]
@manmay-nakhashi yes we can, absolutely :)). But it's not straight forward, you need some trick to do that :)) i will let you do :D.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai i have tried few things but i am stuck at saved_model not working while using model._build(), can you help me with that ?

**Comment by dathudeptrai** [comment]
Hi, i can help you save entire model to pb file. For tflite you need modify a model class :)) eliminate build, inference function and use only call function :)). That is all thing i can help
You now, sorry.

**Comment by manmay-nakhashi** [comment]
i can do that

**Comment by manmay-nakhashi** [comment]
if you can help me with saving entire model to pb file that would be good. apparently i have been trying from some time but it is not working correctly.

**Comment by dathudeptrai** [comment]
@manmay-nakhashi https://github.com/dathudeptrai/TensorflowTTS/blob/master/notebooks/fastspeech_inference.ipynb
