### ISSUE TITLE
FastSpeech 2

### ISSUE THREAD

**Issue by loretoparisi** [dathudeptrai/TensorflowTTS#38]
Hello, thank you for this project. I'm aware of two different implementations of FastSpeech, any plan to support the recent [FastSpeech 2](https://arxiv.org/abs/2006.04558) architecture?

Thank you very much.

**Comment by dathudeptrai** [comment]
@loretoparisi yes, i have a plan :))). But because it's a new paper so i won't public it soon when i finished implementation :D.

**Comment by superhg2012** [comment]
Hi, I am reanding Fastspeech2 paper. could you help to explain how to perform quantize F0 and energy with log-scale bins for f0 and uniform bins for energy?

**Comment by dathudeptrai** [comment]
@superhg2012 i haven't read paper in detail yet. This is what i think, when you compute F0 (f0 value in range 0 - 100 for example) then we have 10 bins (f0 from 0 - 9 in bin 1, f0 from 10-19 in bin 2...) then we will learn 10 f0 embeddings for each bin :))). The procedure is the same for energy

**Comment by ZDisket** [comment]
Is the latest released FastSpeech V3 = FastSpeech 2?

**Comment by dathudeptrai** [comment]
@ZDisket nope :)). it's fastspeech V3 :(. I'm trying to find free time to implement fastspeech v2, fastspeech v2 is not hard to implement, almost layers already implemented on this framework

**Comment by superhg2012** [comment]
> @superhg2012 i haven't read paper in detail yet. This is what i think, when you compute F0 (f0 value in range 0 - 100 for example) then we have 10 bins (f0 from 0 - 9 in bin 1, f0 from 10-19 in bin 2...) then we will learn 10 f0 embeddings for each bin :))). The procedure is the same for energy. But note that before we separate bins we need apply function F to F0 and energy to rescale it, seems paper use log function :D

In FastSpeech2 paper,  they quantize F0 and energy of each frame to 256 possible values.

**Comment by dathudeptrai** [comment]
@superhg2012 yes, after you apply log function to F0, u can quantize it to any posible values. 256 is just 1 option :D. Example after apply log, min f0 is 0 and max f0 is 20, so you can calculate the range of each bins ((20 - 0) / 256) = 0.078125. So all f0 values in range 0, 0.078125 will quantize to 0, f0 values in range 0.078125, 0.078125*2 will quantize to 1, ... then we just need to learn 256 f0 embeddings.

**Comment by rishikksh20** [comment]
@superhg2012 I have tried bit: https://colab.research.google.com/drive/1rGHRPuWMJkNW9g5AS4UhPQSVtdwXX7Nv?usp=sharing

**Comment by superhg2012** [comment]
@dathudeptrai  get it! thanks very much

**Comment by dathudeptrai** [comment]
@rishikksh20 @superhg2012 note that the min and max should be compute on all traing set :))).

**Comment by rishikksh20** [comment]
Yes

**Comment by superhg2012** [comment]
@dathudeptrai  you mean the min and max should be computed from all dataset and then use it to compute bins and then apply bin to each wave?
