### ISSUE TITLE
TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type int32 of argument 'input'.

### ISSUE THREAD

**Issue by abylouw** [dathudeptrai/TensorflowTTS#50]
I am training on CPU machine to make sure everything is okay before moving to GPU machine. 
I get to 500 steps (first evaluation) and get the following type error in the attached 
[log.txt](https://github.com/dathudeptrai/TensorflowTTS/files/4807502/log.txt)

I figure out which feature is the issue?

**Comment by dathudeptrai** [comment]
I can fix it when i come home :))) there is a mismatch between internal code and public code sorry :)). Can you remove input signature on eval steps and check?

**Comment by ChintanDonda** [comment]
I'm also facing the same issue with the below error while trying to feed in the input tensor of **dtype=tf.bfloat16**.

FYI, input tensor (3D image) goes to keras.layers.Conv2D layer.
I want to pass the input tensor with dtype=tf.bfloat16 only.

Error:
**TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type bfloat16 of argument 'input'.**

Any idea on how to fix this?
Thanks in advance.

**Comment by dathudeptrai** [comment]
@ChintanDonda let try dtype=tf.bfloat16 for conv2d .

**Comment by YasaswiniU** [comment]
I'm also facing the same issue with the below error but I cannot find out where.


model.add(Conv2D(32, (5,5), input_shape=(image_x, image_y, 1), activation='relu', padding='same'))

or  

model.fit(train_images1, train_labels1, validation_data=(test_images1, test_labels1), epochs=100, batch_size=100, callbacks=callbacks_list)

-----------------------------------------------------


TypeError: Input 'filter' of 'Conv2D' Op has type float32 that does not match type int32 of argument 'input'.
