### ISSUE TITLE
Error when loading data for train tacotron2 model

### ISSUE THREAD

**Issue by linhld0811** [dathudeptrai/TensorflowTTS#58]
when i load my own dataset to training tacotron2 model, i got this error:

> tensorflow.python.framework.errors_impl.DataLossError: Attempted to pad to a smaller size than the input element. [Op:IteratorGetNext]

Can anyone help me to fixed this error.

**Comment by dathudeptrai** [comment]
Can u set use_fixed_shapes on config file to False or adjust max_mel_len and max_char_len to adapt with ur dataset

**Comment by dathudeptrai** [comment]
re-open if this issue still occur :D.
