### ISSUE TITLE
Optimizer error at the start of training

### ISSUE THREAD

**Issue by sujeendran** [dathudeptrai/TensorflowTTS#59]
Hi,
I notice this error at the start of training every time after loading data although the training starts and progresses as usual. I have a bit of hard time trying to get the model to converge and that's when i started to doubt if the optimizer is having any issue. Is this normal?

![image](https://user-images.githubusercontent.com/30560413/85408820-51632d80-b565-11ea-97c3-46d8e504496b.png)

**Comment by dathudeptrai** [comment]
Normal :)

**Comment by sujeendran** [comment]
Ok thank you.
