### ISSUE TITLE
melgan residual stack config

### ISSUE THREAD

**Issue by superhg2012** [dathudeptrai/TensorflowTTS#65]
Hi, In original melgan paper, the kernel size of the second conv1d layer is 3, I see that in this melgan residual config it's 1.  Is it a better config?

**Comment by dathudeptrai** [comment]
Hi, i didn’t know that, i follow the official code on github and the kernel size is 1.

**Comment by superhg2012** [comment]
> Hi, i didn’t know that, i follow the official code on github and the kernel size is 1.

could you give a link on the official code?

**Comment by dathudeptrai** [comment]
@superhg2012 here, https://github.com/descriptinc/melgan-neurips/blob/master/mel2wav/modules.py#L80

**Comment by superhg2012** [comment]
@dathudeptrai thxs
